package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String razonSocial;
     private String nombreComercial;
     private String nif;
     private String domicilio;
     private String poblacion;
     private String cp;
     private String provincia;
     private String pais;
     private String tlf1;
     private String email;
     private String paginaWeb;
     private Date fechaAlta;
     private String observaciones;
     private String banco;
     private String codigoPais;
     private String titular;
     private String codCuentaBancaria;
     private String codDevolucion;
     private String codIntCuentaBancaria;
     private String iban;
     private String adeudoSepa;
     private String tipoSecuencia;
     private String referenciaMandato;
     private Date fechaMandato;
     private String bancoAcreedor;
     private String cuentaCliente;
     private String cuentaVentas;
     private String cuentaRecargoFinanciero;
     private String cuentaDto;
     private String cuentaDtoPp;
     private String cuentaPortes;
     private String ntarjeta;
     private Date fechaNacimiento;
     private String puntos;
     private Date fechaVtoPuntos;
     private String eurosReales;
     private Date fechaVtoEuros;
     private String tipoPvp;
     private String dtoArticulo;
     private String dtoFijo;
     private String dtoPp;
     private String riesgo;
     private String tipoFactura;
     private String formaPago;
     private String diasPago;
     private String mesNoPago;
     private String leyMorosidad;
     private String diasPlazoMax;
     private String condicionesPago;
     private String recargoFinanciero;
     private String seAplicaSobre;
     private String bancoDomi;
     private String bancoPobla;
     private String bancoCp;
     private String bancoProv;
     private String bancoPais;
     private String bancoCodigo;
     private String referenciaInterna;
     private String domiciliobanco;
     private String poblacionbanco;
     private String provinciabanco;
     private String cpbanco;
     private String paisbanco;
     private String codigobanco;

    public Cliente() {
    }

    public Cliente(String razonSocial, String nombreComercial, String nif, String domicilio, String poblacion, String cp, String provincia, String pais, String tlf1, String email, String paginaWeb, Date fechaAlta, String observaciones, String banco, String codigoPais, String titular, String codCuentaBancaria, String codDevolucion, String codIntCuentaBancaria, String iban, String adeudoSepa, String tipoSecuencia, String referenciaMandato, Date fechaMandato, String bancoAcreedor, String cuentaCliente, String cuentaVentas, String cuentaRecargoFinanciero, String cuentaDto, String cuentaDtoPp, String cuentaPortes, String ntarjeta, Date fechaNacimiento, String puntos, Date fechaVtoPuntos, String eurosReales, Date fechaVtoEuros, String tipoPvp, String dtoArticulo, String dtoFijo, String dtoPp, String riesgo, String tipoFactura, String formaPago, String diasPago, String mesNoPago, String leyMorosidad, String diasPlazoMax, String condicionesPago, String recargoFinanciero, String seAplicaSobre, String bancoDomi, String bancoPobla, String bancoCp, String bancoProv, String bancoPais, String bancoCodigo, String referenciaInterna, String domiciliobanco, String poblacionbanco, String provinciabanco, String cpbanco, String paisbanco, String codigobanco) {
       this.razonSocial = razonSocial;
       this.nombreComercial = nombreComercial;
       this.nif = nif;
       this.domicilio = domicilio;
       this.poblacion = poblacion;
       this.cp = cp;
       this.provincia = provincia;
       this.pais = pais;
       this.tlf1 = tlf1;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.fechaAlta = fechaAlta;
       this.observaciones = observaciones;
       this.banco = banco;
       this.codigoPais = codigoPais;
       this.titular = titular;
       this.codCuentaBancaria = codCuentaBancaria;
       this.codDevolucion = codDevolucion;
       this.codIntCuentaBancaria = codIntCuentaBancaria;
       this.iban = iban;
       this.adeudoSepa = adeudoSepa;
       this.tipoSecuencia = tipoSecuencia;
       this.referenciaMandato = referenciaMandato;
       this.fechaMandato = fechaMandato;
       this.bancoAcreedor = bancoAcreedor;
       this.cuentaCliente = cuentaCliente;
       this.cuentaVentas = cuentaVentas;
       this.cuentaRecargoFinanciero = cuentaRecargoFinanciero;
       this.cuentaDto = cuentaDto;
       this.cuentaDtoPp = cuentaDtoPp;
       this.cuentaPortes = cuentaPortes;
       this.ntarjeta = ntarjeta;
       this.fechaNacimiento = fechaNacimiento;
       this.puntos = puntos;
       this.fechaVtoPuntos = fechaVtoPuntos;
       this.eurosReales = eurosReales;
       this.fechaVtoEuros = fechaVtoEuros;
       this.tipoPvp = tipoPvp;
       this.dtoArticulo = dtoArticulo;
       this.dtoFijo = dtoFijo;
       this.dtoPp = dtoPp;
       this.riesgo = riesgo;
       this.tipoFactura = tipoFactura;
       this.formaPago = formaPago;
       this.diasPago = diasPago;
       this.mesNoPago = mesNoPago;
       this.leyMorosidad = leyMorosidad;
       this.diasPlazoMax = diasPlazoMax;
       this.condicionesPago = condicionesPago;
       this.recargoFinanciero = recargoFinanciero;
       this.seAplicaSobre = seAplicaSobre;
       this.bancoDomi = bancoDomi;
       this.bancoPobla = bancoPobla;
       this.bancoCp = bancoCp;
       this.bancoProv = bancoProv;
       this.bancoPais = bancoPais;
       this.bancoCodigo = bancoCodigo;
       this.referenciaInterna = referenciaInterna;
       this.domiciliobanco = domiciliobanco;
       this.poblacionbanco = poblacionbanco;
       this.provinciabanco = provinciabanco;
       this.cpbanco = cpbanco;
       this.paisbanco = paisbanco;
       this.codigobanco = codigobanco;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getTlf1() {
        return this.tlf1;
    }
    
    public void setTlf1(String tlf1) {
        this.tlf1 = tlf1;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }
    public String getCodCuentaBancaria() {
        return this.codCuentaBancaria;
    }
    
    public void setCodCuentaBancaria(String codCuentaBancaria) {
        this.codCuentaBancaria = codCuentaBancaria;
    }
    public String getCodDevolucion() {
        return this.codDevolucion;
    }
    
    public void setCodDevolucion(String codDevolucion) {
        this.codDevolucion = codDevolucion;
    }
    public String getCodIntCuentaBancaria() {
        return this.codIntCuentaBancaria;
    }
    
    public void setCodIntCuentaBancaria(String codIntCuentaBancaria) {
        this.codIntCuentaBancaria = codIntCuentaBancaria;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getAdeudoSepa() {
        return this.adeudoSepa;
    }
    
    public void setAdeudoSepa(String adeudoSepa) {
        this.adeudoSepa = adeudoSepa;
    }
    public String getTipoSecuencia() {
        return this.tipoSecuencia;
    }
    
    public void setTipoSecuencia(String tipoSecuencia) {
        this.tipoSecuencia = tipoSecuencia;
    }
    public String getReferenciaMandato() {
        return this.referenciaMandato;
    }
    
    public void setReferenciaMandato(String referenciaMandato) {
        this.referenciaMandato = referenciaMandato;
    }
    public Date getFechaMandato() {
        return this.fechaMandato;
    }
    
    public void setFechaMandato(Date fechaMandato) {
        this.fechaMandato = fechaMandato;
    }
    public String getBancoAcreedor() {
        return this.bancoAcreedor;
    }
    
    public void setBancoAcreedor(String bancoAcreedor) {
        this.bancoAcreedor = bancoAcreedor;
    }
    public String getCuentaCliente() {
        return this.cuentaCliente;
    }
    
    public void setCuentaCliente(String cuentaCliente) {
        this.cuentaCliente = cuentaCliente;
    }
    public String getCuentaVentas() {
        return this.cuentaVentas;
    }
    
    public void setCuentaVentas(String cuentaVentas) {
        this.cuentaVentas = cuentaVentas;
    }
    public String getCuentaRecargoFinanciero() {
        return this.cuentaRecargoFinanciero;
    }
    
    public void setCuentaRecargoFinanciero(String cuentaRecargoFinanciero) {
        this.cuentaRecargoFinanciero = cuentaRecargoFinanciero;
    }
    public String getCuentaDto() {
        return this.cuentaDto;
    }
    
    public void setCuentaDto(String cuentaDto) {
        this.cuentaDto = cuentaDto;
    }
    public String getCuentaDtoPp() {
        return this.cuentaDtoPp;
    }
    
    public void setCuentaDtoPp(String cuentaDtoPp) {
        this.cuentaDtoPp = cuentaDtoPp;
    }
    public String getCuentaPortes() {
        return this.cuentaPortes;
    }
    
    public void setCuentaPortes(String cuentaPortes) {
        this.cuentaPortes = cuentaPortes;
    }
    public String getNtarjeta() {
        return this.ntarjeta;
    }
    
    public void setNtarjeta(String ntarjeta) {
        this.ntarjeta = ntarjeta;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(String puntos) {
        this.puntos = puntos;
    }
    public Date getFechaVtoPuntos() {
        return this.fechaVtoPuntos;
    }
    
    public void setFechaVtoPuntos(Date fechaVtoPuntos) {
        this.fechaVtoPuntos = fechaVtoPuntos;
    }
    public String getEurosReales() {
        return this.eurosReales;
    }
    
    public void setEurosReales(String eurosReales) {
        this.eurosReales = eurosReales;
    }
    public Date getFechaVtoEuros() {
        return this.fechaVtoEuros;
    }
    
    public void setFechaVtoEuros(Date fechaVtoEuros) {
        this.fechaVtoEuros = fechaVtoEuros;
    }
    public String getTipoPvp() {
        return this.tipoPvp;
    }
    
    public void setTipoPvp(String tipoPvp) {
        this.tipoPvp = tipoPvp;
    }
    public String getDtoArticulo() {
        return this.dtoArticulo;
    }
    
    public void setDtoArticulo(String dtoArticulo) {
        this.dtoArticulo = dtoArticulo;
    }
    public String getDtoFijo() {
        return this.dtoFijo;
    }
    
    public void setDtoFijo(String dtoFijo) {
        this.dtoFijo = dtoFijo;
    }
    public String getDtoPp() {
        return this.dtoPp;
    }
    
    public void setDtoPp(String dtoPp) {
        this.dtoPp = dtoPp;
    }
    public String getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(String riesgo) {
        this.riesgo = riesgo;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public String getDiasPago() {
        return this.diasPago;
    }
    
    public void setDiasPago(String diasPago) {
        this.diasPago = diasPago;
    }
    public String getMesNoPago() {
        return this.mesNoPago;
    }
    
    public void setMesNoPago(String mesNoPago) {
        this.mesNoPago = mesNoPago;
    }
    public String getLeyMorosidad() {
        return this.leyMorosidad;
    }
    
    public void setLeyMorosidad(String leyMorosidad) {
        this.leyMorosidad = leyMorosidad;
    }
    public String getDiasPlazoMax() {
        return this.diasPlazoMax;
    }
    
    public void setDiasPlazoMax(String diasPlazoMax) {
        this.diasPlazoMax = diasPlazoMax;
    }
    public String getCondicionesPago() {
        return this.condicionesPago;
    }
    
    public void setCondicionesPago(String condicionesPago) {
        this.condicionesPago = condicionesPago;
    }
    public String getRecargoFinanciero() {
        return this.recargoFinanciero;
    }
    
    public void setRecargoFinanciero(String recargoFinanciero) {
        this.recargoFinanciero = recargoFinanciero;
    }
    public String getSeAplicaSobre() {
        return this.seAplicaSobre;
    }
    
    public void setSeAplicaSobre(String seAplicaSobre) {
        this.seAplicaSobre = seAplicaSobre;
    }
    public String getBancoDomi() {
        return this.bancoDomi;
    }
    
    public void setBancoDomi(String bancoDomi) {
        this.bancoDomi = bancoDomi;
    }
    public String getBancoPobla() {
        return this.bancoPobla;
    }
    
    public void setBancoPobla(String bancoPobla) {
        this.bancoPobla = bancoPobla;
    }
    public String getBancoCp() {
        return this.bancoCp;
    }
    
    public void setBancoCp(String bancoCp) {
        this.bancoCp = bancoCp;
    }
    public String getBancoProv() {
        return this.bancoProv;
    }
    
    public void setBancoProv(String bancoProv) {
        this.bancoProv = bancoProv;
    }
    public String getBancoPais() {
        return this.bancoPais;
    }
    
    public void setBancoPais(String bancoPais) {
        this.bancoPais = bancoPais;
    }
    public String getBancoCodigo() {
        return this.bancoCodigo;
    }
    
    public void setBancoCodigo(String bancoCodigo) {
        this.bancoCodigo = bancoCodigo;
    }
    public String getReferenciaInterna() {
        return this.referenciaInterna;
    }
    
    public void setReferenciaInterna(String referenciaInterna) {
        this.referenciaInterna = referenciaInterna;
    }
    public String getDomiciliobanco() {
        return this.domiciliobanco;
    }
    
    public void setDomiciliobanco(String domiciliobanco) {
        this.domiciliobanco = domiciliobanco;
    }
    public String getPoblacionbanco() {
        return this.poblacionbanco;
    }
    
    public void setPoblacionbanco(String poblacionbanco) {
        this.poblacionbanco = poblacionbanco;
    }
    public String getProvinciabanco() {
        return this.provinciabanco;
    }
    
    public void setProvinciabanco(String provinciabanco) {
        this.provinciabanco = provinciabanco;
    }
    public String getCpbanco() {
        return this.cpbanco;
    }
    
    public void setCpbanco(String cpbanco) {
        this.cpbanco = cpbanco;
    }
    public String getPaisbanco() {
        return this.paisbanco;
    }
    
    public void setPaisbanco(String paisbanco) {
        this.paisbanco = paisbanco;
    }
    public String getCodigobanco() {
        return this.codigobanco;
    }
    
    public void setCodigobanco(String codigobanco) {
        this.codigobanco = codigobanco;
    }




}


