package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ordenmostrar generated by hbm2java
 */
public class Ordenmostrar  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private Integer idcliente;
     private String marca;
     private String modelo;

    public Ordenmostrar() {
    }

    public Ordenmostrar(Date fecha, Integer idcliente, String marca, String modelo) {
       this.fecha = fecha;
       this.idcliente = idcliente;
       this.marca = marca;
       this.modelo = modelo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }




}


