package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1



/**
 * Parteabajocoche generated by hbm2java
 */
public class Parteabajocoche  implements java.io.Serializable {


     private Integer id;
     private String obsParteabajo;
     private String materialesabajo;
     private Integer idCliente;

    public Parteabajocoche() {
    }

    public Parteabajocoche(String obsParteabajo, String materialesabajo, Integer idCliente) {
       this.obsParteabajo = obsParteabajo;
       this.materialesabajo = materialesabajo;
       this.idCliente = idCliente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getObsParteabajo() {
        return this.obsParteabajo;
    }
    
    public void setObsParteabajo(String obsParteabajo) {
        this.obsParteabajo = obsParteabajo;
    }
    public String getMaterialesabajo() {
        return this.materialesabajo;
    }
    
    public void setMaterialesabajo(String materialesabajo) {
        this.materialesabajo = materialesabajo;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


