package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1



/**
 * Partearribacoche generated by hbm2java
 */
public class Partearribacoche  implements java.io.Serializable {


     private Integer id;
     private String obsParteArriba;
     private String materialesArriba;
     private Integer idCliente;

    public Partearribacoche() {
    }

    public Partearribacoche(String obsParteArriba, String materialesArriba, Integer idCliente) {
       this.obsParteArriba = obsParteArriba;
       this.materialesArriba = materialesArriba;
       this.idCliente = idCliente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getObsParteArriba() {
        return this.obsParteArriba;
    }
    
    public void setObsParteArriba(String obsParteArriba) {
        this.obsParteArriba = obsParteArriba;
    }
    public String getMaterialesArriba() {
        return this.materialesArriba;
    }
    
    public void setMaterialesArriba(String materialesArriba) {
        this.materialesArriba = materialesArriba;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


