package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1



/**
 * Partedercoche generated by hbm2java
 */
public class Partedercoche  implements java.io.Serializable {


     private Integer id;
     private String obsParteder;
     private String materialesder;
     private Integer idCliente;

    public Partedercoche() {
    }

    public Partedercoche(String obsParteder, String materialesder, Integer idCliente) {
       this.obsParteder = obsParteder;
       this.materialesder = materialesder;
       this.idCliente = idCliente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getObsParteder() {
        return this.obsParteder;
    }
    
    public void setObsParteder(String obsParteder) {
        this.obsParteder = obsParteder;
    }
    public String getMaterialesder() {
        return this.materialesder;
    }
    
    public void setMaterialesder(String materialesder) {
        this.materialesder = materialesder;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


