package satcar6.entity;
// Generated 11-jul-2017 20:30:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reparacion generated by hbm2java
 */
public class ReparacionEntity  implements java.io.Serializable {


     private Integer id;
     private String matricula;
     private String marca;
     private String modelo;
     private String anio;
     private String color;
     private String numMotor;
     private String km;
     private String numBastidor;
     private String combustible;
     private Date fechaHora;
     private Integer cliente;
     private String obsInterna;

    public ReparacionEntity() {
    }

    public ReparacionEntity(String matricula, String marca, String modelo, String anio, String color, String numMotor, String km, String numBastidor, String combustible, Date fechaHora, Integer cliente, String obsInterna) {
       this.matricula = matricula;
       this.marca = marca;
       this.modelo = modelo;
       this.anio = anio;
       this.color = color;
       this.numMotor = numMotor;
       this.km = km;
       this.numBastidor = numBastidor;
       this.combustible = combustible;
       this.fechaHora = fechaHora;
       this.cliente = cliente;
       this.obsInterna = obsInterna;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNumMotor() {
        return this.numMotor;
    }
    
    public void setNumMotor(String numMotor) {
        this.numMotor = numMotor;
    }
    public String getKm() {
        return this.km;
    }
    
    public void setKm(String km) {
        this.km = km;
    }
    public String getNumBastidor() {
        return this.numBastidor;
    }
    
    public void setNumBastidor(String numBastidor) {
        this.numBastidor = numBastidor;
    }
    public String getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(String combustible) {
        this.combustible = combustible;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Integer getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Integer cliente) {
        this.cliente = cliente;
    }
    public String getObsInterna() {
        return this.obsInterna;
    }
    
    public void setObsInterna(String obsInterna) {
        this.obsInterna = obsInterna;
    }




}


